name: build

on:
  push:
    branches:
      - hdoan/deploy_with_env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: '12.16'
    # - name: Install and run unittest
    #   run: |
    #     npm install
    #     npm test
    #   env:
    #     CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: steamforvietnam/Live-at-STEAM/live-steam-dev
        registry: docker.pkg.github.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: master

    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          LMS_BASE_URL: ${{ secrets.LMS_BASE_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        port: ${{ secrets.DROPLET_SSH_PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN, JWT_SECRET_KEY, LMS_BASE_URL, CLIENT_ID, CLIENT_SECRET
        script: |
          docker stop $(docker ps -a -q)
          docker login --username "$GITHUB_USERNAME" --password "$GITHUB_TOKEN" https://docker.pkg.github.com
          docker pull docker.pkg.github.com/steamforvietnam/live-at-steam/live-steam-dev:master
          docker run -dit -p 80:3600 \
            -e JWT_SECRET_KEY -e LMS_BASE_URL -e CLIENT_ID -e
            docker.pkg.github.com/steamforvietnam/live-at-steam/live-steam-dev:master
